# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# test.py
# Created on: 2015-11-18 13:54:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
input_nc = "C:\\608Data\\netcdf\\data\\20140901_20150831_tem2m_0800_step0.nc"
t2m_Layer1 = "t2m_Layer1"
output_tif = "C:\\608Data\\temperature\\temperature08\\t2m_"
tem = "tem_layer"
# Process: Make NetCDF Raster Layer
arcpy.MakeNetCDFRasterLayer_md(input_nc, "t2m", "longitude", "latitude", t2m_Layer1, "time", "", "BY_VALUE")
for i in range(1, 366):
    # Process: Make Raster Layer
    arcpy.MakeRasterLayer_management(t2m_Layer1, tem, "", "DEFAULT", str(i))

    # Process: Copy Raster
    arcpy.CopyRaster_management(tem, output_tif + "JD_" + str((i+243)%365) + ".tif", "", "", "", "NONE", "NONE", "", "NONE", "NONE")

    print i

